### ISSUE TITLE
Higher Level Visualization Framework

### ISSUE THREAD

**Issue by sirinath** [arrayfire/forge#100]
Higher level visualisation framework like https://www.mapd.com/, http://www.vtk.org/, Tableau

Support the working of Data in multiple formats and sources including live and streaming data. Also see: http://www.infoworld.com/article/2983953/nosql/how-to-choose-a-nosql-analytics-system.html

**Comment by 9prady9** [comment]
The goal of forge is to provide rendering logic only i.e. the data provided to forge is expected to be readily passed onto OpenGL buffers. I think the support for massaging data in other formats into the one expected by OpenGL is better handled by data-conversion routines either written by specific user or another library. It falls outside of the scope of forge.
