### ISSUE TITLE
Support building forge with a system install of glbinding

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/forge#104]
Just to be proactive here, I intend to package `forge` to enable the graphics functionalities of `arrayfire` in Debian. Since `forge` now depends on `glbinding`, I also have to package the latter (which is almost done).

Please consider supporting a build of `forge` using a system installation of `glbinding`. [`globjects`](https://github.com/cginternals/globjects/blob/master/source/globjects/CMakeLists.txt) shows how to discover and integrate `glbinding` into a client target.

Cheers,

**Comment by shehzan10** [comment]
We had this in mind and made it a part of #103.

**Comment by ghisvail** [comment]
:+1:

sorry for the duplicate.
