### ISSUE TITLE
Bad colormaps

### ISSUE THREAD

**Issue by kryptan** [arrayfire/forge#122]
Colormaps are defined in src/backend/cmap.hpp in sRGB colorspace.

0. Default (gray) colormap is defined by linearly increasing gray values. This linear increase happens in the sRGB colorspace. One should probably use linearly increasing values in a perceptually uniform colorspace so that e.g. 0.8 is perceptually 2x brighter than 0.4. For gray values sRGB is close so it is not a big deal but something better should probably be used.

1. Spectrum. Its name suggests that it represents spectral colors. However pure spectral colors lie outside of the sRGB colorspace (as can be seen from the CIE chromaticity diagram for sRGB) and thus cannot be displayed on most modern monitors. The best thing we can do here is probably to take some interval, e.g. 400nm - 700nm, so that value 0.0 will correspondent to 400nm, 1.0 to 700nm and calculate sRGB colors closest to the spectral ones on this interval. I have not done this but I think that currently specified colormap is nowhere near it (maybe it is, but it must be verified).

2. Colors. Comment says "pure colors" without any clarification of what does it mean. This colormap has different flaws. First of all it is not perceptually uniform, there are almost flat areas interleaved with abrupt changes. Also it contains colors of different brightness even though it looks like it was meant not to.

3. Red. This looks legit.

4. Mood. This looks legit.

5. Heat. It is defined only by 64 points and there is no interpolation between them, this results in a very noticeable banding. It is also highly perceptually non-uniform.
![heat](https://cloud.githubusercontent.com/assets/11528855/20326204/d1470bb4-ab98-11e6-988d-409bb856dc68.png)

6. Blue. There is an abrupt change in this one near 200.
![blue](https://cloud.githubusercontent.com/assets/11528855/20326191/c2ded480-ab98-11e6-8e47-a6b0d2833595.png)

I suggest to add [colormaps designed for matplotlib](https://bids.github.io/colormap/) and remove of fix others.

It is important to have good colormaps, e.g. when bad colormaps are used in medicine they [can lead to misdiagnosis](http://www.eecs.harvard.edu/~kgajos/papers/2011/borkin11-infoviz.pdf).

**Comment by pavanky** [comment]
@kryptan 

Thanks for providing detailed feedback. If you are willing, you can send a PR to the forge library with the changes :)

**Comment by 9prady9** [comment]
@kryptan & @pavanky Can you please check the changes i made to spectrum color map in the below PR.
https://github.com/arrayfire/forge/pull/123

**Comment by pavanky** [comment]
@9prady9 I have no idea about this :) but please make sure the places you are picking these from are licensed appropriately.

**Comment by 9prady9** [comment]
@kryptan Any suggestions for improving (0) - Grayscale color map ?

**Comment by kryptan** [comment]
@9prady9 The [page](https://bids.github.io/colormap/) I linked above has a link to a tool for generating good colormaps (see Appendix).
