### ISSUE TITLE
The quality of rendering

### ISSUE THREAD

**Issue by deism** [arrayfire/forge#148]
**What issue(memory leak, slow renders, docs fix etc.) did you face?**
Low quality of rendering and jagged edges comparing with Opencv opengl's rendering.
The image size is 1024x1024, I am not sure if this issue is something about the way of interpolation/resampling such as linear, bicubic, or lanczos, any clues?

**Please check if the issue fulfills these requirements**
- [ ] For code issues, please share a small code stub that can reproduce the issue on our end.
- [ X] For performance issues, please share comparison benchmarks.

Forge Rendering
![1](https://user-images.githubusercontent.com/6513657/28031357-9ce95006-65d9-11e7-972d-74d4e08a4093.png)

Opencv OpenGL Rendering
![2](https://user-images.githubusercontent.com/6513657/28031371-a8543b4a-65d9-11e7-9580-cee8e09009ec.png)

**Other information**:

**Comment by 9prady9** [comment]
@deism It is likely a interpolation/re-sampling issue. Can you please share the code you used to render the image and any resources(images) used by the program. Thank you.

**Comment by 9prady9** [comment]
@deism Closing the issue for now. If you can provide the some code stub and image you used to investigate this further, we can look into it.
