### ISSUE TITLE
forge FTBFS with libglm-dev 0.9.9~a2-1

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/forge#160]
Forwarded from [Debian-Bug#888931](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888931).

The issue is with a recently introduced macro blocking experimental features of the API. It should be just a matter of defining `GLM_ENABLE_EXPERIMENTAL` or ensuring you are not using this code path.

**Comment by 9prady9** [comment]
@ghisvail We don't use quaternion math per say. But if whatever is being used internally uses this GLM_GTX_dual_quaternion, we need to refactor that portion. Thank you for reporting it. Any suggestions on the fix are also appreciated. thank you

**Comment by 9prady9** [comment]
Looks like defining `GLM_ENABLE_EXPERIMENTAL` is the easy way out. But that would require a fix again in future when this is removed.

**Comment by 9prady9** [comment]
@ghisvail I have removed the header that caused the issue in PR #161 . Can you please test this change and let me know if it fixed the problem. Thank you.

**Comment by 9prady9** [comment]
@ghisvail Can you please confirm if the PR fixed the problem on debian.

**Comment by 9prady9** [comment]
I have merged the PR. Please reopen the issue if it is still an issue on Debian.
