### ISSUE TITLE
old cmake can not detect target Freetype::Freetype

### ISSUE THREAD

**Issue by pkestene** [arrayfire/forge#178]
**What issue(memory leak, slow renders, docs fix etc.) did you face?**

build system / cmake : 
since last commit the way Freetype library is handled in forge's CMakeLists has changed.
My platform is Ubuntu 17.10, cmake version is 3.5, and target Freetype::Freetype is not defined in cmake 3.5, only since 3.10 (available Ubuntu 18.04).

This is just a suggestion: keep a locally defined cmake module for Freetype::Freetype; this would help users during transition to newest cmake version.

**Comment by 9prady9** [comment]
@pkestene Forge releases we have done so far and the Forge tags used by ArrayFire still have the capability to use Freetype without having `Freetype::Freetype` target defined. It is only in the master branch, which is the development branch, that I removed old functionality in favor of the modern CMake approach. The intention is to avoid having any Find scripts inside Forge project and let cmake handle find scipts to have a better cross platform usability.
