### ISSUE TITLE
Doesn't build against glbinding 3.0

### ISSUE THREAD

**Issue by svenstaro** [arrayfire/forge#183]
This currently fails to compile against glbinding 3 on Arch Linux. Probably don't need to post build logs as you'll run into these problems yourself and they are definitely API problems.

**Comment by 9prady9** [comment]
Hi , We are aware of this issue and we will make the switch as soon as we
can. The main issue is most distributions still has 2.* Versions.

- Pradeep

**Comment by svenstaro** [comment]
At least for Arch Linux, I can only update glbinding once forge compiles
against it.

**Comment by 9prady9** [comment]
@svenstaro It would be great if you can send those changes in as a PR.

**Comment by svenstaro** [comment]
I currently have no time to do that I'm afraid.

**Comment by 9prady9** [comment]
That is fine, we will push the necessary changes as soon as we can. Thanks for reporting it.

**Comment by svenstaro** [comment]
Any chance you can do that soon? I'd like to update glbinding in Arch soon, if possible.

**Comment by 9prady9** [comment]
@svenstaro The main concern for me with forge to use glbinding 3.0 is none of the package managers updated it to 3.0. Even bionic still uses 2.1.1. Also, since ArrayFire uses forge, I would have to bump up that as well which would be issue on Ubuntu like distributions. I am not sure how is this resolved generally. @umar456 @pavanky Any suggestions ?

**Comment by 9prady9** [comment]
While waiting, I am working on code changes for forge to make it compile against 3.0.

**Comment by 9prady9** [comment]
Although compilation fixes are done. Oddly, glsl shader compilation is failing. I will keep you posted.

**Comment by 9prady9** [comment]
@svenstaro master compiles with glbinding 3.0.2 right now. I have couple of more fixes inline which will be on master by EOD. I will do a fix release soon after that.

**Comment by 9prady9** [comment]
@svenstaro v1.0.3 with glbinding 3.0 support is released. Sorry about the delay.
