### ISSUE TITLE
how to save plot image

### ISSUE THREAD

**Issue by zdgithub** [arrayfire/forge#194]
I want to save the plot image instead of displaying it. But I don't find the proper function.
```
const static int width = 512, height = 512;
af::Window window(width, height, "2D plot example title");
do{
array X = seq(-af::Pi, af::Pi, 0.01);
array Y = sin(X);
window.plot(X, Y);
} while( !window.close() );
```

**Comment by 9prady9** [comment]
Window has a method saveFrameBuffer.

**Comment by zdgithub** [comment]
> Window has a method saveFrameBuffer.

I can't find the function in http://arrayfire.org/docs/classaf_1_1Window.htm

**Comment by zdgithub** [comment]
Thank you! I have found it in http://arrayfire.org/forge/classforge_1_1Window.htm#a7b42bb1b6fe76015118491ca1c9f7e84
