### ISSUE TITLE
Forge fails to run (compile is fine) in OpenCL mode in Intel Arc A750 device

### ISSUE THREAD

**Issue by olegmikul** [arrayfire/forge#240]
Compiling Forge is fine for CPU and OpenCL, of coarse I don't have CUDA. Some other applications compiled and run in OpenCL mode. However, for Forge I have the window open, but then an exception happened: 
**terminate called after throwing an instance of 'std::runtime_error'
  what():  No CL-GL sharing contexts found**

How to resolve that? I am a big fun for ArrayFire (started on Nvidia GPU and CUDA), so now I would like to enable it on Intel Arc devices. 

Thank you, 
Oleg

**Comment by umar456** [comment]
I think the current set of Intel a770 drivers do not support OpenCL and OpenGL interop. You should be able to use forge using the CPU API but its not going to be as responsive. I think you should still get pretty good results with this limitation. Perhaps Intel will add this feature to their OpenCL implementation soon. See the following issue:

https://github.com/intel/compute-runtime/issues/166

**Comment by olegmikul** [comment]
Yes, it was my suspicion, also. Thanks! Will contact Intel driver team.
