### ISSUE TITLE
Are non-f32 type objects supported for af_draw_plot in Arrayfire?

### ISSUE THREAD

**Issue by CsatiZoltan** [arrayfire/forge#40]
I experienced that `f64`, `c32` and `c64` causes an error. Will they be supported later on?

**Comment by shehzan10** [comment]
There are a couple of things at play here:
OpenGL does not support double precision. Hence forge does not support any double precision data. Whether the user provides us with double precision and forge then converts it to single precision, or whether the user himself converts it to single precision makes no difference in performance. Hence we require the user to provide f32 data.

With regards to complex, I assume you want it to be shown as a 4-quadrant graph with real and imaginary as the 2 axis. Right now we dont, support it, but I do think that is something we should support for c32.

**Comment by 9prady9** [comment]
@CsatiZoltan Both f64, c64 which are double precision would not be supported. This is so because OpenGL rendering pipeline will eventually truncate the precision to 32-bit, therefore there is no point in supporting these types. 

We can add support for c32 in future

**Comment by CsatiZoltan** [comment]
Ok, thanks.
