### ISSUE TITLE
FindForge.cmake only installed if BUILD_EXAMPLES=ON

### ISSUE THREAD

**Issue by marbre** [arrayfire/forge#51]
I am currently working on an Gentoo ebuild for forge. I noticed that the CMake stuff is only installed if `-DBUILD_EXAMPLES=ON` is passed:

~~~
-- Installing: /var/tmp/portage/sci-visualization/forge-9999/image/usr/share/Forge/examples/CMakeLists.txt
-- Installing: /var/tmp/portage/sci-visualization/forge-9999/image/usr/share/Forge/examples/CMakeModules
-- Installing: /var/tmp/portage/sci-visualization/forge-9999/image/usr/share/Forge/examples/CMakeModules/FindOpenCL.cmake
-- Installing: /var/tmp/portage/sci-visualization/forge-9999/image/usr/share/Forge/examples/CMakeModules/FindForge.cmake
-- Installing: /var/tmp/portage/sci-visualization/forge-9999/image/usr/share/Forge/examples/CMakeModules/FindGLEWmx.cmake
~~~
Otherwise, only the forge library and headers get installed. Initally I expected that only `FindForge.cmake` would be installed. `FindOpenGL.cmake` and a `FindGLEW.cmake` are provided by the system.

Furthermore, I tried to change the install destination with `-DFG_INSTALL_CMAKE_DIR="${ED}/usr/share/cmake/Modules"` which shows no effect. Maybe you can give me a hint.

**Comment by shehzan10** [comment]
We need to make the installation for forge better. I'll work on this.
We will probably change this to use config.cmake files.

**Comment by marbre** [comment]
At the moment, it is not a problem if the installed `FindForge.cmake` is not found, since a `FindForge.cmake` it is provided with ArrayFire anyway. Further, single files can be easily installed within an Gentoo ebuild. For the Gentoo ebuild, there is currently no need to hurry improving this.

Anyway, this might impact other users, thus the report.

**Comment by shehzan10** [comment]
Agreed. That was one of the main reasons why we didn't dedicate resources to improve it.

**Comment by shehzan10** [comment]
@glehmann Would you be interested in contributing the CMake scripts for Forge too? I remember you contributed the ones for ArrayFire. Forge should be much simpler.
