### ISSUE TITLE
Erroneous vertical line in plot3_cpu example

### ISSUE THREAD

**Issue by bkloppenborg** [arrayfire/forge#78]
As shown below, the `plot3_cpu` example has a vertical line in the "funnel" whereas the line does not appear in `plot3_cuda` or `plot3_opencl`. This appears in code from PR #74 .

![screenshot from 2016-03-03 10-47-17](https://cloud.githubusercontent.com/assets/858450/13500234/a54ef9c4-e12f-11e5-9be5-557f4e260828.png)

**Comment by 9prady9** [comment]
@syurkevi Can you please look into it.
