### ISSUE TITLE
Incorrect z-depth buffering in surface_cuda and surface_cpu

### ISSUE THREAD

**Issue by bkloppenborg** [arrayfire/forge#79]
In the code for PR #74, z-depth buffering appears to be broken for (at least) surface plots in the CPU and CUDA backends. See the plots below.

The following image is taken from `surface_opencl` and shows correct z-depth behavior:
![screenshot from 2016-03-03 11-07-46](https://cloud.githubusercontent.com/assets/858450/13500405/669176d4-e130-11e5-8325-2fe093ebb38f.png)

The following image is taken from `surface_cuda` and shows INCORRECT z-depth behavior:
![screenshot from 2016-03-03 11-07-59](https://cloud.githubusercontent.com/assets/858450/13500406/66938636-e130-11e5-979d-6b6b0a16ff54.png)

The following image is taken from `surface_cpu` and shows INCORRECT z-depth behavior:
![screenshot from 2016-03-03 11-08-08](https://cloud.githubusercontent.com/assets/858450/13500404/668eb00c-e130-11e5-9788-5ac83e3e2903.png)

**Comment by 9prady9** [comment]
Fixed in #74
