### ISSUE TITLE
histogram example is incorrect

### ISSUE THREAD

**Issue by bkloppenborg** [arrayfire/forge#81]
There are (at least) two issues here with the histogram example:

1. The Perlin distribution should result in a Gaussian-like distribution of noise, whereas the histogram does not display anything remotely close to this, and 
2. There appears to be a plotting error wherein every 3n and 4n  values are near zero in the histogram.

The Perlin distribution used  in the histograms should [result in a Gaussian-like noise distribution](http://stackoverflow.com/questions/9549851/uniform-distribution-from-a-fractal-perlin-noise-function-in-c-sharp); however, in the examples, it is anything but Gaussian:

![5a349626-e132-11e5-9654-ed3c3b8d0596](https://cloud.githubusercontent.com/assets/858450/13504058/bdb985d6-e140-11e5-8558-b639875468d4.png)

This is even more apparent if one increases the number of bins to around 100:

![screenshot from 2016-03-03 13-08-41](https://cloud.githubusercontent.com/assets/858450/13504135/269846a0-e141-11e5-83b2-2c586531bb11.png)

Also, there appears to be an odd pattern wherein every 3rd and 4th value on the x-axis is near zero.

**Comment by 9prady9** [comment]
@bkloppenborg and @syurkevi I fixed histogram example in api_changes branch. Here are the images.

![screenshot from 2016-03-04 10-59-39](https://cloud.githubusercontent.com/assets/3270458/13518937/eb0e8b72-e1f8-11e5-8138-4a33a1c32bc7.png)
![screenshot from 2016-03-04 10-59-41](https://cloud.githubusercontent.com/assets/3270458/13518938/eb1aba50-e1f8-11e5-9b63-ede69b260339.png)
![screenshot from 2016-03-04 10-59-42](https://cloud.githubusercontent.com/assets/3270458/13518939/eb2479dc-e1f8-11e5-80a5-6b4943fd3c5d.png)
![screenshot from 2016-03-04 10-59-43](https://cloud.githubusercontent.com/assets/3270458/13518940/eb29b4e2-e1f8-11e5-948f-d40731691bc0.png)

**Comment by 9prady9** [comment]
I will do similar code changes in CUDA and OpenCL backend.

FYI - These are only changes in example code, the rendering code doesn't have any bugs.
