### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/forge#84]
- [x] Documentation
- [x] Vendor Neutral Copy Headers
- [x] Improve Mouse based rotation interaction
- ~[ ] Fix rendering bugs on AMD GPUs~
- [x] 2D Vector Fields
- [x] Test Examples on Primary Platforms(Linux, OSX & WIndows)
- [x] Test Examples on Multiple GPU Vendors
- [x] Update `cl.hpp` in examples to use `cl2.hpp` and add that as external project for examples.

Optionally
- [x] glbinding switch
- [x] 3D Vector Fields

**Comment by ghisvail** [comment]
How soon do you think forge 1.0.0 will be released? Just to know whether I'll have enough time to ship it for the freeze for the next release of Debian.

**Comment by 9prady9** [comment]
@ghisvail We are planning to release 1.0 along with ArrayFire's 3.5 release which is around first week of February.

**Comment by shehzan10** [comment]
We do not need to wait until the completion of ArrayFire 3.5 to make this release. We make make it when Forge is deemed ready for v1.0.

@ghisvail What is the timeline for the debian freeze?

**Comment by ghisvail** [comment]
The freeze is scheduled for Feb 5th and packages need 10 days to transition currently. This means the latest for a new upload is around Jan 25th. Nevermind, we'll keep Forge 0.9.x and AF 3.4.2 for Stretch.

**Comment by 9prady9** [comment]
@ghisvail We just made Forge's v1.0 release

**Comment by ghisvail** [comment]
@9prady9 Thanks for the heads-up. I noticed the SOVERSION was left to 0. Can you confirm whether this new release is still API/ABI compatible with the 0.9.x series, please?

**Comment by 9prady9** [comment]
@ghisvail There is one change to a class that breaks compatibility of 1.0 with 0.9.x series. Not setting SOVERSION was by mistake, any suggestions on how to fix this ? or 1.0.1 is the only way ?

**Comment by ghisvail** [comment]
> There is one change to a class that breaks compatibility of 1.0 with 0.9.x series.

You'd need to fix the SOVERSION then.

> or 1.0.1 is the only way ?

Accurate SOVERSION management is important enough to justify making a hotfix release, I believe.

**Comment by 9prady9** [comment]
@ghisvail I fixed it and release v1.0.1.
