### ISSUE TITLE
Cannot load default config file

### ISSUE THREAD

**Issue by dendisuhubdy** [arrayfire/forge#87]
C02QH2D7G8WM:opencl userone$ ./histogram_opencl 
Fontconfig error: Cannot load default config file
Freetype face initilization(3001)
C02QH2D7G8WM:opencl userone$ ./plot
-bash: ./plot: No such file or directory
C02QH2D7G8WM:opencl userone$ ./plot3_opencl 
Fontconfig error: Cannot load default config file
Freetype face initilization(3001)

**Comment by shehzan10** [comment]
Can you provide more information about your system? Are you using Linux or OSX? And which branch of forge are you testing?

**Comment by 9prady9** [comment]
@dendisuhubdy Can you please let us know if you are still facing the issue you mentioned above.

**Comment by 9prady9** [comment]
Closing, please reopen if you are still facing the problem.
